name: windows-gcc-install-and-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Download GCC
      run : > 
        dir &&
        curl --output mingw64 --url https://github.com/brechtsanders/winlibs_mingw/releases/download/13.2.0-16.0.6-11.0.0-ucrt-r1/winlibs-x86_64-posix-seh-gcc-13.2.0-llvm-16.0.6-mingw-w64ucrt-11.0.0-r1.7z

    - name: Unzip GCC
      run : >
        dir &&
        tar -xvzf mingw64

    - name: Test GCC Dir
      run : >
        cd mingw64 &&
        dir &&
        cd bin &&
        dir &&
        cd ../..

    - name: Add GCC to Path
      run : >
        dir &&
        set PATH=%PATH%;%CD%/mingw64/bin
