name: windows-gcc-install-and-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Download GCC
      run : |
        curl -LJO "https://github.com/brechtsanders/winlibs_mingw/releases/download/13.2.0-16.0.6-11.0.0-ucrt-r1/winlibs-x86_64-posix-seh-gcc-13.2.0-llvm-16.0.6-mingw-w64ucrt-11.0.0-r1.zip"
        dir

    - name: Unzip GCC
      run : |
        mkdir MingW64
        tar -xvzf "winlibs-x86_64-posix-seh-gcc-13.2.0-llvm-16.0.6-mingw-w64ucrt-11.0.0-r1.zip" -C MingW64
        dir

    - name: Test GCC Dir
      run : |
        cd MingW64
        dir
        

    # - name: Add GCC to Path
    #   run : >
    #     dir &&
    #     set PATH=%PATH%;%CD%/mingw64/bin
